# -*- coding: utf-8 -*-
"""Data Mining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yHzR-5TBR84txBmMzJ3P1sz1DYdN1rJd
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df = pd.read_excel("../content/dataset_properti.xlsx")

df.info()

label_encoder = LabelEncoder()

df['province_encoded'] = label_encoder.fit_transform(df['province'])

df['city_encoded'] = label_encoder.fit_transform(df['city'])

df['district_encoded'] = label_encoder.fit_transform(df['district'])

print(df)

df.head()

df.isna().sum()

df_model = df[["price","buildingSize","landSize","bedRooms","bathRooms","garages","province_encoded","city_encoded","district_encoded"]]

rf_reg = RandomForestRegressor()

from sklearn.metrics import mean_squared_error, r2_score

x = df_model[["buildingSize","landSize","bedRooms","bathRooms","garages"]]
y = df_model[["price"]]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=71)

rf_reg.fit(X_train, y_train)

y_pred = rf_reg.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mse = mean_squared_error(y_test, y_pred)
r2score = r2_score(y_test, y_pred)

print("RMSE:", rmse)
print("MSE:", mse)
print("R2 Score:", r2score)

Inp_buildingSize = int(input("Masukkan Luas Bangunan: "))
Inp_landSize = int(input("Masukkan Luas Tanah: "))
unit_bedRooms = int(input("Masukkan Banyak Kamar Tidur: "))
unit_bathRooms = int(input("Masukkan Banyak Kamar Mandi: "))
unit_garages = int(input("Masukkan Banyak Garasi: "))

price = int(rf_reg.predict([[Inp_buildingSize, Inp_landSize, unit_bedRooms, unit_bathRooms, unit_garages]]))
price_format = "{:,.0f}".format(price).replace(",", ".")
print("Harga Prediksi Propert Sebesar Rp" + price_format)